name: test-tencentcloud-cli

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: mingshun/tencentcloud-cli-action@master
      with:
        secret_id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
        secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
        region: "guangzhou" 
        commands: help && version
        output_format: json
